# -----------------------------------------------------
# Monitor Setup
# name: "Default"
# -----------------------------------------------------

monitor= , preferred , auto , 1
monitor= , preferred , auto , 1
