# -----------------------------------------------------
# Monitor Setup
# name: "Default"
# -----------------------------------------------------

monitor= , preferred , auto , 1, left
monitor= , preferred , auto , 1, primary, right
